export { default as ResourcePage } from "./Resource"
export { default as WorkerPage } from "./Worker"
export { default as EquipmentPage } from "./Equipment"
export { default as MaterialPage } from "./Material"
export { default as ResourceClassPage } from "./ResourceClass"
