export const RESOURCE_MOCK_DATA = [
    {
        id: "101",
        name: "Tên 1",
        type: "Loại 1",
    },
    {
        id: "102",
        name: "Tên 2",
        type: "Loại 2",
    },
    {
        id: "103",
        name: "Tên 3",
        type: "Loại 3",
    },
    {
        id: "104",
        name: "Tên 4",
        type: "Loại 4",
    },
    {
        id: "105",
        name: "Tên 5",
        type: "Loại 5",
    },
    {
        id: "106",
        name: "Tên 6",
        type: "Loại 6",
    },
    {
        id: "103",
        name: "Tên 3",
        type: "Loại 3",
    },
    {
        id: "104",
        name: "Tên 4",
        type: "Loại 4",
    },
    {
        id: "105",
        name: "Tên 5",
        type: "Loại 5",
    },
    {
        id: "106",
        name: "Tên 6",
        type: "Loại 6",
    },
    {
        id: "103",
        name: "Tên 3",
        type: "Loại 3",
    },
    {
        id: "104",
        name: "Tên 4",
        type: "Loại 4",
    },
    {
        id: "105",
        name: "Tên 5",
        type: "Loại 5",
    },
    {
        id: "106",
        name: "Tên 6",
        type: "Loại 6",
    },
    {
        id: "104",
        name: "Tên 4",
        type: "Loại 4",
    },
    {
        id: "105",
        name: "Tên 5",
        type: "Loại 5",
    },
    {
        id: "106",
        name: "Tên 6",
        type: "Loại 6",
    },
    {
        id: "104",
        name: "Tên 4",
        type: "Loại 4",
    },
    {
        id: "105",
        name: "Tên 5",
        type: "Loại 5",
    },
    {
        id: "106",
        name: "Tên 6",
        type: "Loại 6",
    },
]

export const WORKER_INFO_MOCK_DATA = [
    {
        id: "em-m-1",
        name: "Nguyễn Văn 1",
        type: "Bộ phận 1, Bộ phận 2",
        description: "Mô tả cho nhân viên 1",
    },
    {
        id: "em-m-2",
        name: "Nguyễn Văn 2",
        type: "Bộ phận 2",
        description: "Mô tả cho nhân viên 2",
    },
    {
        id: "em-m-3",
        name: "Nguyễn Văn 3",
        type: "Bộ phận 3",
        description: "Mô tả cho nhân viên 3",
    },
    {
        id: "em-m-4",
        name: "Nguyễn Văn 4",
        type: "Bộ phận 4",
        description: "Mô tả cho nhân viên 4",
    },
    {
        id: "em-m-5",
        name: "Nguyễn Văn 5",
        type: "Bộ phận 5, Bộ phận 6",
        description: "Mô tả cho nhân viên 5",
    },
    {
        id: "em-m-6",
        name: "Nguyễn Văn 6",
        type: "Bộ phận 6",
        description: "Mô tả cho nhân viên 6",
    },
    {
        id: "em-m-7",
        name: "Nguyễn Văn 7",
        type: "Bộ phận 7",
        description: "Mô tả cho nhân viên 7",
    },
    {
        id: "em-m-8",
        name: "Nguyễn Văn 8",
        type: "Bộ phận 8",
        description: "Mô tả cho nhân viên 8",
    },
    {
        id: "em-m-1",
        name: "Nguyễn Văn 1",
        type: "Bộ phận 1, Bộ phận 2",
        description: "Mô tả cho nhân viên 1",
    },
    {
        id: "em-m-2",
        name: "Nguyễn Văn 2",
        type: "Bộ phận 2",
        description: "Mô tả cho nhân viên 2",
    },
    {
        id: "em-m-3",
        name: "Nguyễn Văn 3",
        type: "Bộ phận 3",
        description: "Mô tả cho nhân viên 3",
    },
    {
        id: "em-m-4",
        name: "Nguyễn Văn 4",
        type: "Bộ phận 4",
        description: "Mô tả cho nhân viên 4",
    },
    {
        id: "em-m-5",
        name: "Nguyễn Văn 5",
        type: "Bộ phận 5, Bộ phận 6",
        description: "Mô tả cho nhân viên 5",
    },
    {
        id: "em-m-6",
        name: "Nguyễn Văn 6",
        type: "Bộ phận 6",
        description: "Mô tả cho nhân viên 6",
    },
    {
        id: "em-m-7",
        name: "Nguyễn Văn 7",
        type: "Bộ phận 7",
        description: "Mô tả cho nhân viên 7",
    },
    {
        id: "em-m-8",
        name: "Nguyễn Văn 8",
        type: "Bộ phận 8",
        description: "Mô tả cho nhân viên 8",
    },
    {
        id: "em-m-1",
        name: "Nguyễn Văn 1",
        type: "Bộ phận 1, Bộ phận 2",
        description: "Mô tả cho nhân viên 1",
    },
    {
        id: "em-m-2",
        name: "Nguyễn Văn 2",
        type: "Bộ phận 2",
        description: "Mô tả cho nhân viên 2",
    },
    {
        id: "em-m-3",
        name: "Nguyễn Văn 3",
        type: "Bộ phận 3",
        description: "Mô tả cho nhân viên 3",
    },
    {
        id: "em-m-4",
        name: "Nguyễn Văn 4",
        type: "Bộ phận 4",
        description: "Mô tả cho nhân viên 4",
    },
    {
        id: "em-m-5",
        name: "Nguyễn Văn 5",
        type: "Bộ phận 5, Bộ phận 6",
        description: "Mô tả cho nhân viên 5",
    },
    {
        id: "em-m-6",
        name: "Nguyễn Văn 6",
        type: "Bộ phận 6",
        description: "Mô tả cho nhân viên 6",
    },
    {
        id: "em-m-7",
        name: "Nguyễn Văn 7",
        type: "Bộ phận 7",
        description: "Mô tả cho nhân viên 7",
    },
    {
        id: "em-m-8",
        name: "Nguyễn Văn 8",
        type: "Bộ phận 8",
        description: "Mô tả cho nhân viên 8",
    },
]

export const EQUIPMENT_INFO_MOCK_DATA = [
    {
        id: "eqm-m-1",
        name: "Thiết bị 1",
        type: "Bộ phận 1, Bộ phận 2",
        description: "Mô tả cho thiết bị 1",
    },
    {
        id: "eqm-m-2",
        name: "Thiết bị 2",
        type: "Loại thiết bị 2",
        description: "Mô tả cho thiết bị 2",
    },
    {
        id: "eqm-m-3",
        name: "Thiết bị 3",
        type: "Loại thiết bị 3",
        description: "Mô tả cho thiết bị 3",
    },
    {
        id: "eqm-m-4",
        name: "Thiết bị 4",
        type: "Loại thiết bị 4",
        description: "Mô tả cho thiết bị 4",
    },
    {
        id: "eqm-m-5",
        name: "Thiết bị 5",
        type: "Loại thiết bị 5, Loại thiết bị 6",
        description: "Mô tả cho thiết bị 5",
    },
    {
        id: "eqm-m-6",
        name: "Thiết bị 6",
        type: "Loại thiết bị 6",
        description: "Mô tả cho thiết bị 6",
    },
    {
        id: "eqm-m-7",
        name: "Thiết bị 7",
        type: "Loại thiết bị 7",
        description: "Mô tả cho thiết bị 7",
    },
    {
        id: "eqm-m-8",
        name: "Thiết bị 8",
        type: "Loại thiết bị 8",
        description: "Mô tả cho thiết bị 8",
    },
    {
        id: "eqm-m-1",
        name: "Thiết bị 1",
        type: "Loại thiết bị 1, Loại thiết bị 2",
        description: "Mô tả cho thiết bị 1",
    },
    {
        id: "eqm-m-2",
        name: "Thiết bị 2",
        type: "Loại thiết bị 2",
        description: "Mô tả cho thiết bị 2",
    },
    {
        id: "eqm-m-3",
        name: "Thiết bị 3",
        type: "Loại thiết bị 3",
        description: "Mô tả cho thiết bị 3",
    },
    {
        id: "eqm-m-4",
        name: "Thiết bị 4",
        type: "Loại thiết bị 4",
        description: "Mô tả cho thiết bị 4",
    },
    {
        id: "eqm-m-5",
        name: "Thiết bị 5",
        type: "Loại thiết bị 5, Loại thiết bị 6",
        description: "Mô tả cho thiết bị 5",
    },
    {
        id: "eqm-m-6",
        name: "Thiết bị 6",
        type: "Loại thiết bị 6",
        description: "Mô tả cho thiết bị 6",
    },
    {
        id: "eqm-m-7",
        name: "Thiết bị 7",
        type: "Loại thiết bị 7",
        description: "Mô tả cho thiết bị 7",
    },
    {
        id: "eqm-m-8",
        name: "Thiết bị 8",
        type: "Loại thiết bị 8",
        description: "Mô tả cho thiết bị 8",
    },
    {
        id: "eqm-m-1",
        name: "Thiết bị 1",
        type: "Loại thiết bị 1, Loại thiết bị 2",
        description: "Mô tả cho thiết bị 1",
    },
    {
        id: "eqm-m-2",
        name: "Thiết bị 2",
        type: "Loại thiết bị 2",
        description: "Mô tả cho thiết bị 2",
    },
    {
        id: "eqm-m-3",
        name: "Thiết bị 3",
        type: "Loại thiết bị 3",
        description: "Mô tả cho thiết bị 3",
    },
    {
        id: "eqm-m-4",
        name: "Thiết bị 4",
        type: "Loại thiết bị 4",
        description: "Mô tả cho thiết bị 4",
    },
    {
        id: "eqm-m-5",
        name: "Thiết bị 5",
        type: "Loại thiết bị 5, Loại thiết bị 6",
        description: "Mô tả cho thiết bị 5",
    },
    {
        id: "eqm-m-6",
        name: "Thiết bị 6",
        type: "Loại thiết bị 6",
        description: "Mô tả cho thiết bị 6",
    },
    {
        id: "eqm-m-7",
        name: "Thiết bị 7",
        type: "Loại thiết bị 7",
        description: "Mô tả cho thiết bị 7",
    },
    {
        id: "eqm-m-8",
        name: "Thiết bị 8",
        type: "Loại thiết bị 8",
        description: "Mô tả cho thiết bị 8",
    },
]
